SchoolManagement/Controllers/EmployeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.DAL;
using SchoolManagement.Models.Entity;
using SchoolManagement.Models.ViewModels;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using CrystalDecisions.Shared;
using SchoolManagement.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net.Mail;

namespace SchoolManagement.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeController : Controller
    {
        private SchoolDbContext db = new SchoolDbContext();
        ApplicationDbContext dbm = new ApplicationDbContext();
        

        public ActionResult Index()
        {
            return View(db.Employee.ToList());
        }

        
        public ActionResult Details(int? id)
        {
            List<EmployeeVM> empList = new List<EmployeeVM>();
            List<EmployeeEducation> EduList = new List<EmployeeEducation>();
            List<EmploymentHistory> HistoryList = new List<EmploymentHistory>();
            List<JobInfo> jobInfo = new List<JobInfo>();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = db.Employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            var empEdu = db.EmployeeEducation.Where(i => i.EmployeeId == id).ToList();
            var empHist = db.EmploymentHistory.Where(i => i.EmployeeId == id).ToList();
            var job = db.JobInfo.Where(i => i.EmployeeId == id).FirstOrDefault();
            #region retrieve Education
            foreach (var data in empEdu)
            {
                var educationLavel = db.EducationLevel.Where(i => i.Id == data.EducationLevelId).FirstOrDefault();
                var title = db.ExamTitle.Where(i => i.EducationLevelId == educationLavel.Id).FirstOrDefault();

                EmployeeEducation ed = new EmployeeEducation();
               
                ed.Id = data.Id;
                ed.EducationLevelId = data.EducationLevelId;
                ed.EducationLevel = educationLavel;
                ed.ExamTitle = title;
                ed.ExamTitleId = data.ExamTitleId;
                ed.Major = data.Major;
                ed.InstituteName = data.InstituteName;
                ed.ResultType = data.ResultType;
                ed.CGPA = data.CGPA;
                ed.Scale = data.Scale;
                ed.Marks = data.Marks;
                ed.PassingYear = data.PassingYear;
                ed.Achievement = data.Achievement;
                ed.EmployeeId = data.EmployeeId;
                EduList.Add(ed);

            }
            #endregion
            #region retrieve History
            foreach (var data in empHist)
            {
                EmploymentHistory hist = new EmploymentHistory();
                hist.Id = data.Id;
                hist.CompanyName = data.CompanyName;
                hist.CompanyLocation = data.CompanyLocation;
                hist.Designation = data.Designation;
                hist.From = data.From;
                hist.To = data.To;
                hist.EmployeeId = data.EmployeeId;
                HistoryList.Add(hist);

            }
            #endregion
            #region retrieve JobInfo
            jobInfo.Add(job);
            #endregion
            #region bind in Viewmodel
            EmployeeVM vm = new EmployeeVM
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    FatherName = employee.FatherName,
                    MotherName = employee.MotherName,
                    Gender = employee.Gender,
                    DOB = employee.DOB,
                    MaritalStatus = employee.MaritalStatus,
                    Religion = employee.Religion,
                    Nationality = employee.Nationality,
                    NID = employee.NID,
                    PresentAddress = employee.PresentAddress,
                    PermanentAddress = employee.PermanentAddress,
                    Phone = employee.Phone,
                    Email = employee.Email,
                    Image = employee.Image,
                    UserName = employee.UserName,
                    EmployeeEducation = EduList,
                    EmploymentHistory = HistoryList,
                    JobInfo = jobInfo


                };
                empList.Add(vm);
            #endregion
             
            ViewBag.EducationLevelId = new SelectList(db.EducationLevel, "Id", "EducationLevelNaame");
            ViewBag.ExamTitleId = new SelectList(db.ExamTitle, "Id", "TitleName");
            return View(empList.FirstOrDefault());
        }

        public ActionResult PrintEmployee(int? id)
        {

            List<EmployeeVM> empList = new List<EmployeeVM>();
            List<EmployeeEducation> EduList = new List<EmployeeEducation>();
            List<EmploymentHistory> HistoryList = new List<EmploymentHistory>();
            List<JobInfo> jobInfo = new List<JobInfo>();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = db.Employee.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            var empEdu = db.EmployeeEducation.Where(i => i.EmployeeId == id).ToList();
            var empHist = db.EmploymentHistory.Where(i => i.EmployeeId == id).ToList();
            var job = db.JobInfo.Where(i => i.EmployeeId == id).FirstOrDefault();
            #region retrieve Education
            foreach (var data in empEdu)
            {
                var educationLavel = db.EducationLevel.Where(i => i.Id == data.EducationLevelId).FirstOrDefault();
                var title = db.ExamTitle.Where(i => i.EducationLevelId == educationLavel.Id).FirstOrDefault();

                EmployeeEducation ed = new EmployeeEducation();

                ed.Id = data.Id;
                ed.EducationLevelId = data.EducationLevelId;
                ed.EducationLevel = educationLavel;
                ed.ExamTitle = title;
                ed.ExamTitleId = data.ExamTitleId;
                ed.Major = data.Major;
                ed.InstituteName = data.InstituteName;
                ed.ResultType = data.ResultType;
                ed.CGPA = data.CGPA;
                ed.Scale = data.Scale;
                ed.Marks = data.Marks;
                ed.PassingYear = data.PassingYear;
                ed.Achievement = data.Achievement;
                ed.EmployeeId = data.EmployeeId;
                EduList.Add(ed);

            }
            #endregion
            #region retrieve History
            foreach (var data in empHist)
            {
                EmploymentHistory hist = new EmploymentHistory();
                hist.Id = data.Id;
                hist.CompanyName = data.CompanyName;
                hist.CompanyLocation = data.CompanyLocation;
                hist.Designation = data.Designation;
                hist.From = data.From;
                hist.To = data.To;
                hist.EmployeeId = data.EmployeeId;
                HistoryList.Add(hist);

            }
            #endregion
            #region retrieve JobInfo
            jobInfo.Add(job);
            #endregion
            #region bind in Viewmodel
            EmployeeVM vm = new EmployeeVM
            {
                Id = employee.Id,
                Name = employee.Name,
                FatherName = employee.FatherName,
                MotherName = employee.MotherName,
                Gender = employee.Gender,
                DOB = employee.DOB,
                MaritalStatus = employee.MaritalStatus,
                Religion = employee.Religion,
                Nationality = employee.Nationality,
                NID = employee.NID,
                PresentAddress = employee.PresentAddress,
                PermanentAddress = employee.PermanentAddress,
                Phone = employee.Phone,
                Email = employee.Email,
                Image = employee.Image,
                UserName = employee.UserName,
                EmployeeEducation = EduList,
                EmploymentHistory = HistoryList,
                JobInfo = jobInfo


            };
            empList.Add(vm);
            #endregion
            return View(empList.FirstOrDefault());
        }
        [HttpPost]
        public ActionResult CreateEducation(EmployeeVM viewModel, int id)
        {
            try
            {
                EmployeeEducation edu = new EmployeeEducation();

                edu.EducationLevelId = viewModel.EducationLevelId;
                edu.ExamTitleId = viewModel.ExamTitleId;
                edu.Major = viewModel.Major;
                edu.InstituteName = viewModel.InstituteName;
                edu.ResultType = viewModel.ResultType;
                edu.Scale = viewModel.Scale;
                edu.CGPA = viewModel.CGPA;
                edu.Marks = viewModel.Marks;
                edu.PassingYear = viewModel.PassingYear;
                edu.Duration = viewModel.Duration;
                edu.Achievement = viewModel.Achievement;
                edu.EmployeeId = id;
                db.EmployeeEducation.Add(edu);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = id });
            }
            catch (Exception ex)
            {

                //TempData["Toastr"] = Toastr.DbError(ex.Message);
            }

            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public ActionResult CreateEmployment(EmployeeVM viewModel, int id)
        {

SchoolManagement/Views/Employe/Create.cshtml
@model SchoolManagement.Models.ViewModels.EmployeeVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "Employe", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="page-header">
        <h1>
            Add Enployee
            <small>
                <i class="ace-icon fa fa-angle-double-right"></i>
                @Html.ActionLink("Back to List", "Index")
            </small>
        </h1>
    </div>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MotherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MotherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MotherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaritalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaritalStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaritalStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Religion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Religion,"--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Religion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PresentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PresentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PresentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PermanentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PermanentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PermanentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="EmployeeImage" required />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Role, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Role", null, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.Label("Role", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Role", null, new { @class = "form-control" })
                @Html.ValidationMessage("Role", "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}

SchoolManagement/Views/Employe/Edit.cshtml
@model SchoolManagement.Models.Entity.Employee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>
        Edit Employee
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            @Html.ActionLink("Back to List", "Index")
        </small>
    </h1>
</div>
@using (Html.BeginForm("Edit", "Employe", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MotherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MotherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MotherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaritalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaritalStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaritalStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Religion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Religion, "--Select--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Religion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PresentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PresentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PresentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PermanentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PermanentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PermanentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="EmployeeImage" required />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                 @{
                        if(Model.Image !=null)
                        {
                            var base64 = Convert.ToBase64String(Model.Image);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            <img src='@imgSrc' style="max-width:100px; max-height:100px;" />
                        }
                      
                    }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}